//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;
using Frank.Libraries.Xml.Models.StandardBusinessDocument;

namespace Frank.Extensions.Xml
{
    /// <remarks/>
    [GeneratedCode("xsd", "4.8.3928.0")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace =
        "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [XmlRoot(
        Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader", IsNullable = false)]
    public partial class StandardBusinessDocumentHeader
    {

        private string _headerVersionField;

        private Partner[] _senderField;

        private Partner[] _receiverField;

        private DocumentIdentification _documentIdentificationField;

        private Manifest _manifestField;

        private Scope[] _businessScopeField;

        /// <remarks/>
        public string HeaderVersion
        {
            get => _headerVersionField;
            set => _headerVersionField = value;
        }

        /// <remarks/>
        [XmlElement("Sender")]
        public Partner[] Sender
        {
            get => _senderField;
            set => _senderField = value;
        }

        /// <remarks/>
        [XmlElement("Receiver")]
        public Partner[] Receiver
        {
            get => _receiverField;
            set => _receiverField = value;
        }

        /// <remarks/>
        public DocumentIdentification DocumentIdentification
        {
            get => _documentIdentificationField;
            set => _documentIdentificationField = value;
        }

        /// <remarks/>
        public Manifest Manifest
        {
            get => _manifestField;
            set => _manifestField = value;
        }

        /// <remarks/>
        [XmlArrayItem(IsNullable = false)]
        public Scope[] BusinessScope
        {
            get => _businessScopeField;
            set => _businessScopeField = value;
        }
    }
}