//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Frank.Libraries.SBDH
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("Partner", Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class Partner
    {

        [Required()]
        [XmlElement("Identifier")]
        public PartnerIdentification Identifier { get; set; }

        [XmlIgnore()]
        private Collection<ContactInformation> _contactInformation;

        [XmlElement("ContactInformation")]
        public Collection<ContactInformation> ContactInformation
        {
            get
            {
                return this._contactInformation;
            }
            private set
            {
                this._contactInformation = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ContactInformation-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the ContactInformation collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool ContactInformationSpecified
        {
            get
            {
                return (this.ContactInformation.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Partner" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Partner" /> class.</para>
        /// </summary>
        public Partner()
        {
            this._contactInformation = new Collection<ContactInformation>();
        }
    }
}
