//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Cefact.Namespaces.StandardBusinessDocumentHeader
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("BusinessService", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("BusinessService", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class BusinessService
    {
        
        [XmlElement("BusinessServiceName")]
        public string BusinessServiceName { get; set; }
        
        [XmlElement("ServiceTransaction")]
        public ServiceTransaction ServiceTransaction { get; set; }
    }
}
