//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Cefact.Namespaces.StandardBusinessDocumentHeader
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("CorrelationInformation", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("CorrelationInformation", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class CorrelationInformation
    {
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [XmlElement("RequestingDocumentCreationDateTime", DataType="dateTime")]
        public DateTime RequestingDocumentCreationDateTimeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die RequestingDocumentCreationDateTime-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the RequestingDocumentCreationDateTime property is specified.</para>
        /// </summary>
        [XmlIgnore()]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool RequestingDocumentCreationDateTimeValueSpecified { get; set; }
        
        [XmlIgnore()]
        public Nullable<DateTime> RequestingDocumentCreationDateTime
        {
            get
            {
                if (this.RequestingDocumentCreationDateTimeValueSpecified)
                {
                    return this.RequestingDocumentCreationDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.RequestingDocumentCreationDateTimeValue = value.GetValueOrDefault();
                this.RequestingDocumentCreationDateTimeValueSpecified = value.HasValue;
            }
        }
        
        [XmlElement("RequestingDocumentInstanceIdentifier")]
        public string RequestingDocumentInstanceIdentifier { get; set; }
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [XmlElement("ExpectedResponseDateTime", DataType="dateTime")]
        public DateTime ExpectedResponseDateTimeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die ExpectedResponseDateTime-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the ExpectedResponseDateTime property is specified.</para>
        /// </summary>
        [XmlIgnore()]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool ExpectedResponseDateTimeValueSpecified { get; set; }
        
        [XmlIgnore()]
        public Nullable<DateTime> ExpectedResponseDateTime
        {
            get
            {
                if (this.ExpectedResponseDateTimeValueSpecified)
                {
                    return this.ExpectedResponseDateTimeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.ExpectedResponseDateTimeValue = value.GetValueOrDefault();
                this.ExpectedResponseDateTimeValueSpecified = value.HasValue;
            }
        }
    }
}
