//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Cefact.Namespaces.StandardBusinessDocumentHeader
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("ServiceTransaction", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ServiceTransaction
    {
        
        [EditorBrowsable(EditorBrowsableState.Never)]
        [XmlAttribute("TypeOfServiceTransaction")]
        public TypeOfServiceTransaction TypeOfServiceTransactionValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die TypeOfServiceTransaction-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the TypeOfServiceTransaction property is specified.</para>
        /// </summary>
        [XmlIgnore()]
        [EditorBrowsable(EditorBrowsableState.Never)]
        public bool TypeOfServiceTransactionValueSpecified { get; set; }
        
        [XmlIgnore()]
        public Nullable<TypeOfServiceTransaction> TypeOfServiceTransaction
        {
            get
            {
                if (this.TypeOfServiceTransactionValueSpecified)
                {
                    return this.TypeOfServiceTransactionValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.TypeOfServiceTransactionValue = value.GetValueOrDefault();
                this.TypeOfServiceTransactionValueSpecified = value.HasValue;
            }
        }
        
        [XmlAttribute("IsNonRepudiationRequired")]
        public string IsNonRepudiationRequired { get; set; }
        
        [XmlAttribute("IsAuthenticationRequired")]
        public string IsAuthenticationRequired { get; set; }
        
        [XmlAttribute("IsNonRepudiationOfReceiptRequired")]
        public string IsNonRepudiationOfReceiptRequired { get; set; }
        
        [XmlAttribute("IsIntelligibleCheckRequired")]
        public string IsIntelligibleCheckRequired { get; set; }
        
        [XmlAttribute("IsApplicationErrorResponseRequested")]
        public string IsApplicationErrorResponseRequested { get; set; }
        
        [XmlAttribute("TimeToAcknowledgeReceipt")]
        public string TimeToAcknowledgeReceipt { get; set; }
        
        [XmlAttribute("TimeToAcknowledgeAcceptance")]
        public string TimeToAcknowledgeAcceptance { get; set; }
        
        [XmlAttribute("TimeToPerform")]
        public string TimeToPerform { get; set; }
        
        [XmlAttribute("Recurrence")]
        public string Recurrence { get; set; }
    }
}
