//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Frank.Libraries.SBDH
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("ManifestItem", Namespace = "http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class ManifestItem
    {

        /// <summary>
        /// <para>The MIME type as defined by IANA. Please refer to
        ///            http://www.iana.org/assignments/media-types/ for a list of types.</para>
        /// </summary>
        [Required()]
        [XmlElement("MimeTypeQualifierCode")]
        public string MimeTypeQualifierCode { get; set; }

        [Required()]
        [XmlElement("UniformResourceIdentifier")]
        public string UniformResourceIdentifier { get; set; }

        [XmlElement("Description")]
        public string Description { get; set; }

        /// <summary>
        /// <para>ISO 639-2; 1998 representation of Language name. Refer to http://www.loc.gov/standards/iso639-2/iso639jac.html to get the latest version of the standard.</para>
        /// </summary>
        [XmlElement("LanguageCode")]
        public string LanguageCode { get; set; }
    }
}
