//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System.CodeDom.Compiler;

namespace Cefact.Namespaces.StandardBusinessDocumentHeader
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    public partial interface IScopeAttributes
    {
        
        string Type
        {
            get;
            set;
        }
        
        string InstanceIdentifier
        {
            get;
            set;
        }
        
        string Identifier
        {
            get;
            set;
        }
    }
}
