//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.444.0.

using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics;
using System.Xml.Serialization;

namespace Cefact.Namespaces.StandardBusinessDocumentHeader
{
    [GeneratedCode("XmlSchemaClassGenerator", "2.0.444.0")]
    [Serializable()]
    [XmlType("StandardBusinessDocumentHeader", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlRoot("StandardBusinessDocumentHeader", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
    public partial class StandardBusinessDocumentHeader
    {
        
        [Required()]
        [XmlElement("HeaderVersion")]
        public string HeaderVersion { get; set; }
        
        [XmlIgnore()]
        private Collection<Partner> _sender;
        
        [Required()]
        [XmlElement("Sender")]
        public Collection<Partner> Sender
        {
            get
            {
                return this._sender;
            }
            private set
            {
                this._sender = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="StandardBusinessDocumentHeader" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="StandardBusinessDocumentHeader" /> class.</para>
        /// </summary>
        public StandardBusinessDocumentHeader()
        {
            this._sender = new Collection<Partner>();
            this._receiver = new Collection<Partner>();
            this._businessScope = new Collection<Scope>();
        }
        
        [XmlIgnore()]
        private Collection<Partner> _receiver;
        
        [Required()]
        [XmlElement("Receiver")]
        public Collection<Partner> Receiver
        {
            get
            {
                return this._receiver;
            }
            private set
            {
                this._receiver = value;
            }
        }
        
        [Required()]
        [XmlElement("DocumentIdentification")]
        public DocumentIdentification DocumentIdentification { get; set; }
        
        [XmlElement("Manifest")]
        public Manifest Manifest { get; set; }
        
        [XmlIgnore()]
        private Collection<Scope> _businessScope;
        
        [XmlArray("BusinessScope")]
        [XmlArrayItem("Scope", Namespace="http://www.unece.org/cefact/namespaces/StandardBusinessDocumentHeader")]
        public Collection<Scope> BusinessScope
        {
            get
            {
                return this._businessScope;
            }
            private set
            {
                this._businessScope = value;
            }
        }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die BusinessScope-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the BusinessScope collection is empty.</para>
        /// </summary>
        [XmlIgnore()]
        public bool BusinessScopeSpecified
        {
            get
            {
                return (this.BusinessScope.Count != 0);
            }
        }
    }
}
