name: Release: signal

on:
  push:
    branches: [main, master]

permissions:
  contents: write

jobs:
  signal_release:
    name: Release: signal
    uses: frankhaugen/Workflows/.github/workflows/dotnet-auto-release-from-signal.yml@main
    secrets: inherit
