name: Pull Request Workflow

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pull_request_job:
    name: Pull Request Job
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    uses: frankhaugen/Workflows/.github/workflows/dotnet-pull-request.yml@main
    secrets: inherit
